rdkcentral/wan-manager

source/WanManager/wanmgr_wan_failover.c
source/WanManager/wanmgr_wan_failover.h

RDKB-55307 : WAN Failover and Restore Timing Metrics
Reason for change: Telemetry log for the time taken to Failover and Restoration. Test Procedure:
Test WanFailOver telemetry logs.
Risks: none
Priority: P1

RDKB-55307 : WAN Failover and Restore Timing Metrics

---

source/WanManager/wanmgr_interface_sm.c

- Wanmanager selects the WAN type and has the voice interface information.
- Wanmanager should update the Voice interface name to TelcoVoiceManager.
Test Procedure: Please refer JIRA attachment for detailed test steps
Risks: None

RDKBDEV-2282: Handling Voice Interface IP (X_RDK_BoundIpAddr)

---

source/WanManager/wanmgr_net_utils.c
source/WanManager/wanmgr_policy_autowan_impl.c
source/WanManager/wanmgr_sysevents.c
source/WanManager/wanmgr_utils.c
source/WanManager/wanmgr_utils.h

use sysctl_iface_set() to write to /proc files
Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>
Priority: P1
Change-Id: Id49e9264a2c53e103f03fa95f68b43f30c63f20e

RDKCOM-4774: RDKBDEV-2643: use sysctl_iface_set() to write to /proc

---

source/TR-181/middle_layer_src/wanmgr_dml_apis.c

fix incorrect change to support 64bit targets
It's not valid to cast a pointer to a 32bit value to be a pointer to a 64bit value.
Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>
Change-Id: I9d7a0c695423986f0574cefd73eee45ac57cafa5

RDKCOM-4784: RDKBDEV-2642 fix incorrect change to support 64bit

---

source/TR-181/middle_layer_src/wanmgr_rbus_handler_apis.c
source/WanManager/wanmgr_dhcpv6_apis.c
source/WanManager/wanmgr_interface_sm.c

Reason for change: Integration with Test and Diagnostic. (step 8)
1) Fixing rbus crash while WCC restart
2) Adding Ipv4, Ipv6 gateway to TAD wan connectivity request.
3) Fixing trigger RestartConnectivityCheck on Ipv6 renew
4) Using primary interface DNS for backup in Comcast products.
Risks: none
Priority: P1
Change-Id: I4b0db02f7b8c79ba9d2e831c41e1869d51360d13

RDKB-54113: Integration with Test and Diagnostic WAN connectivity check.

---

source/WanManager/wanmgr_interface_sm.c

- Set voip interface to voice manager if dedicated voip interface is available.
- Set default wan interface to voice manager if dedicated voip interface is not available.
Test Procedure: Please refer JIRA attachment for detailed test steps
Risks: None

RDKBDEV-2282: Set correct voip interface to voice manager

---

source/WanManager/wanmgr_dhcpv4_apis.c

fix return value from void function WanMgr_UpdateIpFromCellularMgr() Test Procedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>
Priority: P1
Change-Id: I3021ff5d4baa3163d5c412290105e429b4baf95d

RDKCOM-4775: RDKBDEV-2644: fix return value from void

---

source/WanManager/wanmgr_dhcpv6_apis.c

Reason for change: DHCPv6 provisioning fails with dynamic DUID
Test Procedure: Check that DUID remains the same over reboots
Risks: None
Signed-off-by: Pavlov Andrey apavlov@maxlinear.com

RDKDEV-1046 : Fix DHCPv6 dynamic duid issue

---

source/WanManager/wanmgr_data.c
source/WanManager/wanmgr_data.h
source/WanManager/wanmgr_dhcpv4_apis.c

Reason for change: Remove sysevent and implemnt platform api
Test Procedure: No regression in DHCPv4 data model in UI
Risks: Low
Priority: P2
Change-Id: I4da4d800e6014a64182b07ed8293bd9e41cbc7d3

RDKB-55511: Remove RDKB api dependancy from DHCPv4 HAL

---

source/TR-181/middle_layer_src/wanmgr_rdkbus_utils.c

It's the logic error when local variable did not been initialized. The invalid pointer(retVal) was freed by free_parameterValStruct_t because it's not null.

RDKBDEV-2661 fix wan mgr crash for invalid free

---

source/WanManager/wanmgr_sysevents.c

Reason for change: To fix IPv6 address allocation issue for RPI platform.

REFPLTB-3054:Erouter0 is not getting IPv6 address.

---

source/WanManager/wanmgr_dhcp_legacy_apis.c
source/WanManager/wanmgr_dhcpv6_apis.c
source/WanManager/wanmgr_sysevents.c

Reason for change: Zebra-restart will be replaced with dhcpv6_raserver-restart
Test Procedure: 1. Lanmanger event should get triggered when
lanmanager distro is enabled
2. ra.conf file gets created Risks: None
Signed-off-by: raghavendra.hegde2@comcast.com

 RDKB-54270:Changing the zebra-restart event name when lanmanager distro enabled

---

source/WanManager/wanmgr_interface_sm.c
source/WanManager/wanmgr_sysevents.h

IPV6 address changes are not triggering telemetry events
Make a build and check whether IPV6 address changes triggering telemetry events.
Risks: None
Signed-off-by: kavya_chowdahallisuresh@comcast.com

IPV6 address changes are not triggering telemetry events

---

source/WanManager/wanmgr_sysevents.c

RDKB-54039 : IPv6 is taking more than 25 sec to get configured
Reason for change: Setting router_solicitations to 0 while disabling accept_ra for Wan interface Test Procedure:
Verify IPv6 Router Solicitation (RS) and Router Advertisement (RA).
Risks: none
Priority: P1

RDKB-54039 : IPv6 is taking more than 25 sec to get configured

---

source/WanManager/wanmgr_ipc.c

Reason for change: Device.Time.NTPServer1/2 have value with single qoutes while setting as "value". Test Procedure:
1.)Test the DML Device.Time.NTPServer1/2
Risks: High
Priority: P1
Signed-off-by: kulvendra singh <kulvendra.singh@sky.uk>

RDKB-55020:ihc_resolve_domain_name is failed if NTPServer1 is changed

---

source/TR-181/middle_layer_src/wanmgr_rbus_handler_apis.c
source/TR-181/middle_layer_src/wanmgr_rbus_handler_apis.h
source/WanManager/wanmgr_dhcpv4_apis.c
source/WanManager/wanmgr_dhcpv6_apis.c
source/WanManager/wanmgr_interface_sm.c

Reason for change: Implementing below rbus TR181 entries Device.X_RDK_WanManager.Interface.{i}.VirtualInterface.{i}.IP.IPv4Address Device.X_RDK_WanManager.Interface.{i}.VirtualInterface.{i}.IP.IPv6Address
Risks: none
Priority: P1

RDKB-55721: IPv4/v6 Address tr181 implementation

---

config/RdkWanManager.xml
config/RdkWanManager_v2.xml
source/TR-181/middle_layer_src/wanmgr_dml_iface_apis.c
source/TR-181/middle_layer_src/wanmgr_dml_iface_v2_apis.c

Reason for change: Removing EnableIPoEHealthCheck DML Test Procedure:
Risks: none
Priority: P1
Signed-off-by: kulvendra singh <kulvendra.singh@sky.uk>

RDKB-53816 : [Revert] - Remove EnableIPoEHealthCheck DML from WanManager

---

configure.ac
source/TR-181/include/wanmgr_dml.h
source/TR-181/middle_layer_src/wanmgr_dml_iface_v2_apis.c
source/WanManager/Makefile.am
source/WanManager/wanmgr_interface_sm.c
source/WanManager/wanmgr_main.c

Reason for change: Implementaion of Wan health check control from a RFC
Risks: none
Priority: P1

RDKB-56195 : Control DNS health check using RFC in VISM

---

source/TR-181/middle_layer_src/wanmgr_rbus_handler_apis.c
source/TR-181/middle_layer_src/wanmgr_rbus_handler_apis.h
source/WanManager/wanmgr_dhcpv6_apis.c
source/WanManager/wanmgr_interface_sm.c

Reason for change: Using detectedIpv6 Addr if ipv6 address(IANA) is not shared when IPv6 prefix is renewed.
Risks: none
Priority: P1

RDKB-56235: The IPv6 Address DM showing null after IPv6 Renew

---

source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
source/WanManager/wanmgr_main.c

Reverts rdkcentral/RdkWanManager#34
Reverting due to Gtest failure reported in RDKB-56270

Revert "RDKB-54150:webconfig service should only be accessed after Wan UP"

---

source/WanManager/wanmgr_interface_sm.c

Reason for change:  The XDNS configs were not updated to resolv.conf during WAN reconnect.
Risks: Medium
Priority: P1
Signed-off-by: Kanchana karthika <kanchana.karthika@sky.uk>

RDKB-56030 :XDNS is not working for WAN Disconnect/Reconnect and Line Migration

---

source/TR-181/middle_layer_src/wanmgr_dml_iface_apis.c
source/TR-181/middle_layer_src/wanmgr_dml_iface_v2_apis.c
source/TR-181/middle_layer_src/wanmgr_rbus_handler_apis.c
source/WanManager/wanmgr_data.c
source/WanManager/wanmgr_dhcp_legacy_apis.c
source/WanManager/wanmgr_dhcpv6_apis.c
source/WanManager/wanmgr_interface_sm.c
source/WanManager/wanmgr_main.c
source/WanManager/wanmgr_net_utils.c
source/WanManager/wanmgr_policy_auto_impl.c
source/WanManager/wanmgr_sysevents.c

Reason for change: To follow comcast device flow
Test procedure: Sanity wrt IPv4 and IPv6
Risks: Low

REFPLTB-3100: Add RPI flag along side Comcast device flag

---

source/TR-181/middle_layer_src/wanmgr_dml_dhcpv6.c

Reason for change: Wrong interface was passed in case of VDSL, modified to send current wan interface.
Risks: none
Priority: P2

RDKB-51706 : [MAP-T-HUB6] Index update issue in DM -Device.DHCPv6.Client.1.Interface

---

source/WanManager/wanmgr_interface_sm.c

Reason for change: RefreshDHCP Flag was not set to false which led to flooding of logs.
Risks: none
Priority: P2

RDKB-55171:Excessive logging in WANManager on changing the IP Mode

---

source/WanManager/wanmgr_interface_sm.c
source/WanManager/wanmgr_policy_auto_impl.c

Reason for change: Removing Physical status check when interface is in scanning state.
Risks: none
Priority: P1

RDKB-56964 :The AutoWan Selection Timer is not functioning as intended 

---

source/WanManager/wanmgr_sysevents.c

Network response script has not been invoked after wan started due to this LED status was not proper and CP status also not proper.
1. LED should behave properly
2. CP should work without any issue
3. WAN functionality should work without any issue
Risks: Low

CBR2-2096 : [Field][DA] Internet LED fast blinking in 7.6p3s1.

---

source/WanManager/wanmgr_interface_sm.c

Reason for change: Observed WAN going down in CPE , 7 mins after FR and continuous
flooding of "TRANSITION REFRESHING WAN" events seen in logs
1.)Test MAPT Line with FR.
Risks: High
Priority: P1
Signed-off-by: kulvendra singh <kulvendra.singh@sky.uk>

RDKB-57103:Observed WAN going down in CPE , 7 mins after FR

---

source/WanManager/wanmgr_interface_sm.c

Reason for change: Fixing ip_forward proc entry for MAPT platforms
Risks: none
Priority: P1

RDKB-57454 : Fixing ip_forward for MAPT line

---

source/WanManager/wanmgr_policy_auto_impl.c

Reason for change: As Erouter IP is not being restored without Factory-Reset.
Test Procedure: Erouter0 IP should get restored while switching over from LTE to WanOE and on reboots as well.
Risks: None.

RDKCOM-5173 REFPLTB-3128: [TDK][AUTO][RPI4][CELLULAR MANAGER] Switching back to ethwan from cellular mode not working as expected

---

source/TR-181/include/dmsb_tr181_psm_definitions.h
source/TR-181/include/wanmgr_dml.h
source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
source/WanManager/wanmgr_data.c

Supported VLAN Marking operations for Sky XER10 variant.
1. WAN Manager functionality should work without any issue
2. VLAN Marking entries should be present as part of DML, Device.X_RDK_WanManager.Interface.<x>.Marking.
3. Voice Marking should work without any issue
Risks: Low
Signed-off-by: Lakshminarayanan <lakshminarayanan.shenbagaraj2@sky.uk>

XER10-823 : Support VLAN Marking for Sky XER10 variant.

---

configure.ac

Reason for change:  Adding version log using "git describe --tags --always --dirty" command Example :
RC2.7.0a-1-g5aa0583-dirty
Tag: RC2.7.0a (Most recent tag)
Number of Commits Ahead: -1 (1 commit after the tag) Commit Hash: g5aa0583 ( "5aa0583" Hash of the current commit) Uncommitted Changes: -dirty (Changes not yet committed)
Version log should be present.
Priority: P1
Risks: none

RDKB-58019 : Adding version log.

---

source/TR-181/middle_layer_src/wanmgr_rdkbus_utils.c
source/TR-181/middle_layer_src/wanmgr_rdkbus_utils.h
source/WanManager/wanmgr_policy_auto_impl.c
source/WanManager/wanmgr_policy_parallel_scan_impl.c

Reason for change:  WanManager feteches the last reboot reason for the current reboot due to dependencies
* from WebPA and Webconfig on various reboot scenarios (e.g., factory reset, reboot command, etc.).
Risks: none
Priority: P1

SKYH4-7393 : Using last reboot reason for the Wan change reboot

---

source/WanManager/wanmgr_policy_auto_impl.c

Looks like GUI relying on Device.X_RDKCENTRAL-COM_EthernetWAN.CurrentOperationalMode TR181 output where it should be Ethernet but our case it is showing DOCSIS so that is causing MSO login issue when WAN Unification use case.
Corrected the index mapping for DOCSIS and ETHERNET based on ActiveIndex and setting respective curr_wan_mode DB value.
1. MSO page should work without any issue
2. WAN functionality should work without any issue
Risks: Low

XER10-810 : Observed mso page is not accessible with latest Sprint NG Build.

---

source/WanManager/wanmgr_interface_sm.c

Reason for change: if DAD failed on LAN bridge, log an ERROR message and continue with the WAN process.
Risks: none
Priority: P1

RDKB-58499 : Recovery of DAD issue seen

---

source/WanManager/wanmgr_sysevents.c

Reason for change: wwan0 learns it prefix from RA as well which added dual address
Risks: none
Priority: P1

LTE-2565 : Observing dual inet6 addr Scope:Global entries in ifconfig wwan0

---

source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
source/WanManager/wanmgr_interface_sm.c

1. When XLE detected remote device that will be added as part of WAN Interface list and has been selected because of device is in Extender Mode.
2. During this time when we update interface active status CurrentActive interface name has been updated as Mesh interface(br-home). The logic needs to be tuned when updating active interface status in WANManager during XLE switching often between GFO/WFO use case.
1. WANManager functionality should work without any issue
2. Parodus should work without any issue
Risks: Medium
Signed-off-by: LakshminarayananShenbagaraj <lakshminarayanan.shenbagaraj2@sky.uk>

LTE-2585 : Parodus connectivity lost because ActiveInterface_split is "br-home,br-home".

---

source/TR-181/middle_layer_src/wanmgr_rdkbus_apis.c
source/WanManager/wanmgr_interface_sm.c

Telemetry log when the DNS is changed.
Risks: none
Priority: P1

RDKB-58911 : Telemetry log when the DNS is changed.

---

source/WanManager/wanmgr_interface_sm.c
source/WanManager/wanmgr_sysevents.c

SSH service has been not refreshed after MAP-T active during boot-up to avoid this issue.
1. Reversessh should work without any issue.
2. WANManager functionality should work without any issue.
Risks: Low
Signed-off-by: LakshminarayananShenbagaraj <lakshminarayanan.shenbagaraj2@sky.uk>

XER10-1089 : Reverse SSH is not working with PROD builds in MAP-T Line in US.

---

source/WanManager/wanmgr_main.c

Reason for change: Wanmanager processes are running in non-root with rfc control, removing rfc controlled code part Test Procedure: Processes should not be able to switch back to root using RFC  DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.NonRootSupport.Blocklist Risks: Medium
Priority: P1

RDKB-58931: Removing RFC control for non-root processes

---

source/TR-181/middle_layer_src/wanmgr_dml_iface_v2_apis.c

Writing BaseInterface path to PSM when it is set.
Risks: none
Priority: P1

XER10-924 : Writing BaseInterface path to PSM when it is set.

---

source/WanManager/wanmgr_main.c

RDKBDEV-3093 : Clearing capabilities leakage in RdkWanManager
Reason for change: possibly lost: 194 bytes in 1 blocks caused by reading capabilities and not clearing after.
Test Procedure: run valgind with this module
Risks: None
Signed-off-by: Marek Mizinak <Marek.Miziniak@cognizant.com>

RDKCOM-5227 RDKBDEV-3093 : Clearing capabilities leakage in RdkWanManager

---

source/TR-181/middle_layer_src/wanmgr_dml_dhcpv6.c

Default("NONE" display before selecting MAP-T mode) DML handling for MapTransportMode parameter is missing for FEATURE_MAPT use case so this needs to be done.
1. WAN should work without any issue
Risks: Medium

XER10-1052 : MapTransportMode param value is empty after reboot.

---

config/RdkWanManager_v2.xml
source/TR-181/middle_layer_src/wanmgr_rdkbus_utils.c
source/TR-181/middle_layer_src/wanmgr_rdkbus_utils.h
source/WanManager/wanmgr_interface_sm.c
source/WanManager/wanmgr_net_utils.c
source/WanManager/wanmgr_sysevents.c
source/WanManager/wanmgr_utils.c

SHARMAN-3449 : Global ipv6 PD updated on erouter0 instead of brlan0
Replcaing bridge_mode sysevent query with TR181 DML
Risks: none
Priority: P1

SHARMAN-3449 : Global ipv6 pd address updated on erouter0 instead of brlan0 

---

source/WanManager/wanmgr_ssp_messagebus_interface.c

RDKBDEV-3075: remove dependency on dbus
Reason for change:Remove dependency on dbus
Test Procedure: Sanity.
Risks: None.
Signed-off-by:
Andre McCurdy amccurdy@libertyglobal.com
SukanyaIlavarasi sukanya.i@tataelxsi.co.in

RDKCOM-5243 RDKBDEV-3075 remove dependency on dbus

---

source/WanManager/wanmgr_dhcpv6_apis.c

Reason for change:  Custom WanManager version
Risks: none
Priority: P1

RDKB-60471 : Device.Time.TimeOffset returns junk value

---

source/WanManager/wanmgr_webconfig_apis.c

Reason for change: wanmanager crashes when webconfig blob request is processed.
Risks: none
Priority: P2

SHARMAN-3454 : Wanmanager gets Crashed and Not able to reach internet on LAN and WAN due to webconfig post

---

source/WanManager/wanmgr_net_utils.c

Reason for Change: BPI Device Mac is not getting updated in eth_wan_mac sysevent and in AdvSecurity logs
Test Procedure: Build should get compile and eth_wan_mac value should be board MAC address
Risks: Low

RDKBACCL-907: [TDK][AUTO][BPI] CcspAdvSecuritySsp keeps restarting and eth_wan_mac value is not updated

---

configure.ac
source/TR-181/netmonitor/Makefile.am
source/WanManager/Makefile.am

remove dependency on dbus
Test Proedure: Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <amccurdy@libertyglobal.com>

RDKBDEV-3234: remove dependency on dbus

---

source/WanManager/wanmgr_policy_auto_impl.c
source/WanManager/wanmgr_policy_parallel_scan_impl.c

Key Changes:
wanmgr_policy_auto_impl.c
The log message for starting the virtual InterfaceStateMachine now includes Selection.Status. The call to WanMgr_StartWanVISM now passes WAN_IFACE_ACTIVE if Selection.Status is WAN_IFACE_ACTIVE, otherwise it passes WAN_IFACE_SELECTED. wanmgr_policy_parallel_scan_impl.c
Added a log message before starting the InterfaceStateMachine, showing Selection.Status. The call to WanMgr_StartWanVISM now conditionally passes WAN_IFACE_ACTIVE or WAN_IFACE_SELECTED based on Selection.Status. Similar logging and conditional parameter changes were made in another function when handling virtual interface changes.

RDKB-60146 : WAN Interface control Rbus methods

---

source/WanManager/wanmgr_main.c
source/WanManager/wanmgr_t2_telemetry.c

Reason for change: t2_init should be called with simple name and at right place.
Risks: none
Priority: P1

RDKB-61845: In telemetry2_0 Event markers are assigned without component name
